In [1]:
import pandas as pd
import csv
import time

In [2]:
data= pd.read_csv("/Users/malik/Desktop/hocschule/BA/data/instagram_strava.csv")
data

,id_Publication,Date Publication,Second User,Num Likes,Num Words Text,Num Mentions,Num Hashtags,Num Comments,Num TEXT Comments,Num EMOJI Comments,Num EMOJI_TEXT Comments,Num Images,Num Videos,Weekend,Second User Indicator,Text,Images_Videos_order,Image_20240322-0019
0,1,2023-12-31,jonnyrdavies,6943,35,1,3,37,15,3,19,0,1,1,1,AD - 2023 @strava year in sport ️\n\nThese are...,['VIDEO 1_1.mp4'],{}
1,2,2023-12-30,williamgoodge,5176,23,1,0,44,15,2,27,0,1,1,1,A little more interesting than showing you Don...,['VIDEO 2_1.mp4'],{}
2,3,2023-12-29,utmbmontblanc,1822,264,0,4,6,4,1,1,4,0,0,1,58 millions of kilometers all together - 2023 ...,"['Image3_1.png', 'Image3_2.png', 'Image3_3.png...",{'Image 1': 'The image features a man in actio...
3,4,2023-12-28,whoop,3801,45,0,0,33,17,1,15,5,0,0,1,Get ready to jumpstart 2024 with a WHOOP x Str...,"['Image4_1.png', 'Image4_2.png', 'Image4_3.png...",{'Image 1': 'The image features the Strawa & w...
4,5,2023-12-27,NaN,16234,13,0,0,53,32,0,21,0,1,0,1,"We’re on Strava, of course we’re going to tell...",['VIDEO 5_1.mp4'],{}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1510,1578,2018-01-05,NaN,2877,22,1,1,12,8,0,4,2,0,0,1,Celebration: There was plenty of it at the Str...,"['Image1578_1.png', 'Image1578_2.png']",{'Image 1': 'A young man with long dreadlocks ...
1511,1579,2018-01-05,NaN,5378,37,1,2,17,8,1,8,1,0,0,1,What do these photos of the Berlin Marathon an...,['Image1579_1.png'],{'Image 1': 'The image features an exciting co...
1512,1580,2018-01-04,NaN,4098,27,2,1,5,4,0,1,1,0,0,1,Celebration: You can see it on the face of @fr...,['Image1580_1.png'],{'Image 1': 'A close-up photo features a woman...
1513,1581,2018-01-02,NaN,6491,26,1,1,18,10,0,8,1,0,0,1,Stephanie Case after scraping under the 24 hou...,['Image1581_1.png'],{}
1514,1582,2018-01-01,NaN,6033,22,1,1,8,4,0,4,0,1,0,1,"Adventure: These Mountain Bikers in Jackson, W...",['VIDEO 1582_1.mp4'],{}

In [15]:
data= pd.read_csv("/Users/malik/Downloads/llm.csv")
data

,Image Path,folder,Chatbot Reply
0,/tmp/gradio/54e3bbfba43e173336b08b36350240ef26...,3,The image features a group of people in the mi...
1,/tmp/gradio/ac7cb8d2ff82c3b5354fa818ffd040c55d...,3,The image is a green background with two yello...
2,/tmp/gradio/1fa2dc11b85a1bb5ac8d4e31222dd79abd...,3,"The image showcases a banner with the title, ""..."
3,/tmp/gradio/592a851e9cfedd11fd36f07b11885fdded...,3,The image displays a large banner advertising ...
4,/tmp/gradio/3588c3639793dde76c6018e5a835488c12...,640,"In the image, a group of three people, possibl..."
5,/tmp/gradio/7a2b12264fdf48836a93a21d02ff5f7455...,640,A man is seated in a wheelchair with a cooler ...
6,/tmp/gradio/ef0979bdbbd7c11687e5b7be6ec5e0cb3e...,486,The image showcases a man wearing a backpack r...
7,/tmp/gradio/ef31e7cc7804a6a9c8f900446958a07ce9...,475,"The image shows two concentric circles, with o..."
8,/tmp/gradio/32bff1e4d29253ed4ec4c6bc458b8231a0...,475,The image displays a blue and orange backgroun...

In [2]:
#combine the data haven same folder number
def combine_data(csv_file):
    data_dict = {}
    with open(csv_file, 'r') as file:
        csv_reader = csv.reader(file)
        next(csv_reader) 
        for row in csv_reader:
            id_publiction = int(row[1])
            images_data = row[2]
            if id_publiction not in data_dict:
                data_dict[id_publiction] = []
            data_dict[id_publiction].append(images_data)
    return data_dict

In [5]:
data_dict_csv1 = combine_data("/Users/malik/Downloads/llm.csv")
print(data_dict_csv1)

{3: ['The image features a group of people in the middle of an alpine skiing trail, gathered together and carrying their skis. The trail appears to be quite challenging, with a steep slope. There are four people visible in the scene, each with different skis and attire, indicating that they might be competing or participating in a skiing event. \n\n\nThe scene also includes several additional objects scattered across the area. A few bottles are placed at various positions on the mountain slope, with one bottle located close to the left side of the trail, and another located farther right. There is a cell phone in the center of the image, near the middle part of the trail.', 'The image is a green background with two yellow speech bubbles, one at the left side and another at the right side. The bubble on the left side has the text "305 millions toilets saved" in white letters, while the bubble on the right side contains the text "56 million lives improved" in white letters. \n\n\nIn the middle of the scene, there is a golden trophy displayed with the same green color as the background. This trophy symbolizes the achievement in saving toilets and improving lives through efficient toilet solutions.', 'The image showcases a banner with the title, "Kids\' 10k in Miami" prominently placed across the top of it. It highlights the event taking place on November 18th, and is inviting kids to participate in an interactive run on that date. There is also a small picture of two smiling people holding hands in the background of the banner.\n\n\nBelow the main title, there are two smaller sections with more details about the event. The left section describes the race\'s distance – starting with the words, "Run 10k", while the right section provides some vital information about the event\'s location – "Location: Miami". A small map with multiple locations spread throughout the city can be seen below these details, giving children an idea of where the race will take place.\n\n\nOverall, the image effectively promotes the Kids\' 10k in Miami, inviting young participants to register for the exciting event.', 'The image displays a large banner advertising the "2020 stage in sport" event. The banner is colorful and informative, with numerous elements to attract potential attendees. There are numerous people in the background of the image, making it appear to be an active and engaging environment.\n\n\nThe event banner features "Stage in sport" written prominently across the top, while the tagline "DAGABOOM YOUNG SPORT" is placed beneath it. The word "stage" is spelled out in red, yellow, blue, and orange colors, with each letter spread across the banner. The words "young" and "SPORT" appear below the event name and tagline, respectively.'], 640: ['In the image, a group of three people, possibly friends, are running down a dirt path while discussing running with each other. The man on the right side of the group is holding a cellphone in his hand, possibly documenting their run or communicating with others about their exercise plan.', 'A man is seated in a wheelchair with a cooler at his feet, holding a cup of beverage. He appears to be smiling and looking relaxed. The wheelchair has hand brakes on its side, indicating that it is an older model.'], 486: ['The image showcases a man wearing a backpack running on top of a hill. He appears to be enjoying his run in the mountainous landscape, with an interesting scenic view. The person is in the foreground, standing atop the hill and looking over his shoulder, possibly checking the terrain or scanning for any obstacles. \n\nA pair of shoes can also be seen near the runner, possibly indicating that he has taken off his shoes to run barefoot on the hilly terrain. Overall, the atmosphere of the scene suggests an active and adventurous outdoor activity in a natural environment.'], 475: ['The image shows two concentric circles, with one circle depicting the total number of people in the world and the other indicating the number of those who use social media. One circle is much larger, representing a significant percentage of the entire population, while the other circle shows the smaller percentage who utilize social media platforms. The image is in pink background, providing a vibrant contrast to the primary colors.', 'The image displays a blue and orange background with the text "11 million" in bold and white, taking up most of the screen. The text is accompanied by three triangular shapes, each placed on top of one another, with two on the left side and one on the right side, with a small dot near the middle of the right-most triangle.']}

In [3]:
# combine data
#create new colomn , add header in the strava Csv file , add the data from the images in the new updated colomn, place the colomn in csv of strava
def update_csv(csv1, csv2):
    data_dict_csv1 = combine_data(csv1)
    with open(csv2, 'r') as file:
        csv_reader = csv.reader(file)
        updated_colomn = []
        header = next(csv_reader)
        header.extend(["Image_" + time.strftime("%Y%m%d-%H%M")])
        updated_colomn.append(header)
        for colomn_value in csv_reader:
            id_publiction = int(colomn_value[0])
            if id_publiction in data_dict_csv1:
                colomn_value.append({f"Image {i + 1}": data for i, data in enumerate(data_dict_csv1[id_publiction])})
            else:
                colomn_value.append({})
            updated_colomn.append(colomn_value)

    with open(csv2, 'w', newline='') as out_file:
        csv_writer = csv.writer(out_file)
        csv_writer.writerows(updated_colomn)

In [4]:
csv_file1 = "/Users/malik/Desktop/hocschule/BA/Codes/combined.csv"
csv_file2 = "/Users/malik/Desktop/hocschule/BA/data/instagram_strava.csv"

In [17]:
csv2_df = pd.read_csv(csv_file2)
csv2_df.columns

Index(['id_Publication', 'Date Publication', 'Second User', 'Num Likes',
       'Text', 'Num Words Text', 'Num Mentions', 'Num Images', 'Num Videos',
       'Num Comments', 'Num TEXT Comments', 'Num EMOJI Comments',
       'Num EMOJI_TEXT Comments', 'Images_Videos_order', 'Image', 'Image.1',
       'Image_{timestr}', 'Image_20240311-170228', 'Image_20240311-171934',
       'Image_20240311-1720'],
      dtype='object')

In [5]:
update_csv(csv_file1, csv_file2)